TITLE TO ADD NUMBERS LYING BETWEEN 30 AND 100
        .MODEL SMALL
        .DATA
TAB DW 10,100,167,340,22,149,11,53,31,66
SUM DW ?
        .STACK
        .CODE
MAIN PROC FAR
        MOV AX,@DATA
        MOV DS,AX
        MOV AX,0
        LEA BX,TAB
        MOV CX,10
NEXT:   CMP WORD PTR [BX],30
        JBE SKIP
        CMP WORD PTR [BX],100
        JAE SKIP
        ADD AX,[BX]
SKIP:   INC BX
		INC BX
        LOOP NEXT
        MOV SUM,AX
		;converting to ASCII HEXAdecimal
		MOV CX,00H
		MOV BX,16
L1:		MOV DX,0
		DIV BX
		CMP DX,9
		JA HEX
		ADD DX,30H
		JMP NEX
HEX:	ADD DX,37H
NEX:	PUSH DX
		INC CX
		CMP AX,0
		JA L1
		
		MOV AH,02H
DISP:	POP DX
		INT 21H
		LOOP DISP
		
		MOV AX,4C00H
		INT 21H
MAIN	ENDP
END MAIN
		